// Darkmile mock data — Franklin County, Ohio (Columbus market)

export const MOCK_PROPERTIES = [
  {
    id: "prop_001",
    address: "4200 Polaris Pkwy",
    city: "Columbus",
    state: "OH",
    zip: "43240",
    county: "Franklin",
    latitude: 40.1456,
    longitude: -82.9882,
    propertyType: "Office",
    squareFeet: 48500,
    yearBuilt: 2008,
    assessedValue: 7200000,
    lastSalePrice: 9800000,
    lastSaleDate: new Date("2021-03-15"),
    ownerName: "Polaris Corporate Center LLC",
    ownerType: "LLC",
  },
  {
    id: "prop_002",
    address: "1800 Rickenbacker Pkwy",
    city: "Columbus",
    state: "OH",
    zip: "43217",
    county: "Franklin",
    latitude: 39.8354,
    longitude: -82.9237,
    propertyType: "Industrial",
    squareFeet: 220000,
    yearBuilt: 2015,
    assessedValue: 14500000,
    lastSalePrice: 18200000,
    lastSaleDate: new Date("2022-07-22"),
    ownerName: "Rickenbacker Holdings LLC",
    ownerType: "LLC",
  },
  {
    id: "prop_003",
    address: "750 Sawmill Rd",
    city: "Dublin",
    state: "OH",
    zip: "43017",
    county: "Franklin",
    latitude: 40.1051,
    longitude: -83.1141,
    propertyType: "Retail",
    squareFeet: 32000,
    yearBuilt: 1998,
    assessedValue: 4100000,
    lastSalePrice: 5600000,
    lastSaleDate: new Date("2019-11-08"),
    ownerName: "Dublin Square Partners",
    ownerType: "Trust",
  },
  {
    id: "prop_004",
    address: "3900 Easton Way",
    city: "Columbus",
    state: "OH",
    zip: "43219",
    county: "Franklin",
    latitude: 40.0617,
    longitude: -82.9119,
    propertyType: "Retail",
    squareFeet: 18500,
    yearBuilt: 2003,
    assessedValue: 3800000,
    lastSalePrice: 4900000,
    lastSaleDate: new Date("2020-04-30"),
    ownerName: "Easton Retail Trust",
    ownerType: "Trust",
  },
  {
    id: "prop_005",
    address: "6100 Riverside Dr",
    city: "Dublin",
    state: "OH",
    zip: "43017",
    county: "Franklin",
    latitude: 40.0918,
    longitude: -83.1068,
    propertyType: "Office",
    squareFeet: 72000,
    yearBuilt: 2012,
    assessedValue: 11200000,
    lastSalePrice: 14800000,
    lastSaleDate: new Date("2023-01-19"),
    ownerName: "Dublin Corporate Park LP",
    ownerType: "Corporation",
  },
  {
    id: "prop_006",
    address: "900 Goodale Blvd",
    city: "Columbus",
    state: "OH",
    zip: "43212",
    county: "Franklin",
    latitude: 39.9742,
    longitude: -83.0205,
    propertyType: "Office",
    squareFeet: 41000,
    yearBuilt: 2000,
    assessedValue: 5900000,
    lastSalePrice: 7400000,
    lastSaleDate: new Date("2018-09-12"),
    ownerName: "Short North Capital Group",
    ownerType: "LLC",
  },
  {
    id: "prop_007",
    address: "2500 Corporate Exchange Dr",
    city: "Columbus",
    state: "OH",
    zip: "43231",
    county: "Franklin",
    latitude: 40.0821,
    longitude: -82.9317,
    propertyType: "Industrial",
    squareFeet: 180000,
    yearBuilt: 2018,
    assessedValue: 12800000,
    lastSalePrice: 16500000,
    lastSaleDate: new Date("2023-06-07"),
    ownerName: "NorthPoint Development LLC",
    ownerType: "LLC",
  },
  {
    id: "prop_008",
    address: "5500 New Albany Rd",
    city: "New Albany",
    state: "OH",
    zip: "43054",
    county: "Franklin",
    latitude: 40.0851,
    longitude: -82.7908,
    propertyType: "Industrial",
    squareFeet: 350000,
    yearBuilt: 2020,
    assessedValue: 28000000,
    lastSalePrice: 36000000,
    lastSaleDate: new Date("2023-09-15"),
    ownerName: "Amazon.com Services LLC",
    ownerType: "Corporation",
  },
  {
    id: "prop_009",
    address: "3200 Morse Rd",
    city: "Columbus",
    state: "OH",
    zip: "43231",
    county: "Franklin",
    latitude: 40.0571,
    longitude: -82.9418,
    propertyType: "Retail",
    squareFeet: 52000,
    yearBuilt: 1995,
    assessedValue: 4600000,
    lastSalePrice: 5200000,
    lastSaleDate: new Date("2016-02-28"),
    ownerName: "Morse Road Ventures Trust",
    ownerType: "Trust",
  },
  {
    id: "prop_010",
    address: "1600 Dublin Granville Rd",
    city: "Columbus",
    state: "OH",
    zip: "43229",
    county: "Franklin",
    latitude: 40.1108,
    longitude: -83.0139,
    propertyType: "Multifamily",
    squareFeet: 285000,
    units: 240,
    yearBuilt: 2016,
    assessedValue: 32000000,
    lastSalePrice: 41500000,
    lastSaleDate: new Date("2022-11-30"),
    ownerName: "Capitol Square Partners",
    ownerType: "LLC",
  },
  {
    id: "prop_011",
    address: "4800 E Broad St",
    city: "Columbus",
    state: "OH",
    zip: "43213",
    county: "Franklin",
    latitude: 39.9632,
    longitude: -82.8798,
    propertyType: "Industrial",
    squareFeet: 120000,
    yearBuilt: 1985,
    assessedValue: 5800000,
    lastSalePrice: 7100000,
    lastSaleDate: new Date("2017-06-14"),
    ownerName: "East Broad Industrial LLC",
    ownerType: "LLC",
  },
  {
    id: "prop_012",
    address: "200 W Nationwide Blvd",
    city: "Columbus",
    state: "OH",
    zip: "43215",
    county: "Franklin",
    latitude: 39.9648,
    longitude: -83.0062,
    propertyType: "Office",
    squareFeet: 95000,
    yearBuilt: 2006,
    assessedValue: 15200000,
    lastSalePrice: 21000000,
    lastSaleDate: new Date("2024-02-08"),
    ownerName: "Nationwide Arena Partners",
    ownerType: "Corporation",
  },
  {
    id: "prop_013",
    address: "7200 Groveport Rd",
    city: "Groveport",
    state: "OH",
    zip: "43125",
    county: "Franklin",
    latitude: 39.8655,
    longitude: -82.8940,
    propertyType: "Industrial",
    squareFeet: 500000,
    yearBuilt: 2019,
    assessedValue: 38000000,
    lastSalePrice: 49000000,
    lastSaleDate: new Date("2023-04-12"),
    ownerName: "Groveport Logistics Trust",
    ownerType: "Trust",
  },
  {
    id: "prop_014",
    address: "350 E Town St",
    city: "Columbus",
    state: "OH",
    zip: "43215",
    county: "Franklin",
    latitude: 39.9597,
    longitude: -82.9985,
    propertyType: "Multifamily",
    squareFeet: 195000,
    units: 168,
    yearBuilt: 2014,
    assessedValue: 22000000,
    lastSalePrice: 28500000,
    lastSaleDate: new Date("2021-08-19"),
    ownerName: "German Village Residences LP",
    ownerType: "Corporation",
  },
  {
    id: "prop_015",
    address: "1100 S High St",
    city: "Columbus",
    state: "OH",
    zip: "43206",
    county: "Franklin",
    latitude: 39.9446,
    longitude: -82.9995,
    propertyType: "Mixed-Use",
    squareFeet: 28000,
    yearBuilt: 2017,
    assessedValue: 5400000,
    lastSalePrice: 7200000,
    lastSaleDate: new Date("2022-03-25"),
    ownerName: "German Village Dev Partners",
    ownerType: "LLC",
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: "txn_001",
    propertyId: "prop_007",
    transactionType: "sale",
    price: 16500000,
    pricePerSF: 91.67,
    buyer: "NorthPoint Development LLC",
    seller: "Midwest Industrial REIT",
    recordedDate: new Date("2025-05-12"),
    instrumentNumber: "2025-0512-001",
    source: "Franklin County Recorder",
    aiInsight: "Price represents a 7.2% premium over Q4 2024 comparable industrial sales in the Corporate Exchange submarket. Buyer NorthPoint has acquired 3 Columbus industrial assets in 12 months — aggressive expansion signal.",
  },
  {
    id: "txn_002",
    propertyId: "prop_008",
    transactionType: "sale",
    price: 36000000,
    pricePerSF: 102.86,
    buyer: "Amazon.com Services LLC",
    seller: "New Albany Industrial Partners",
    recordedDate: new Date("2025-05-10"),
    instrumentNumber: "2025-0510-003",
    source: "Franklin County Recorder",
    aiInsight: "Amazon's third acquisition in New Albany submarket this cycle. Combined footprint now exceeds 1.1M SF. Surrounding land parcels likely to see 20-35% price appreciation.",
  },
  {
    id: "txn_003",
    propertyId: "prop_012",
    transactionType: "sale",
    price: 21000000,
    pricePerSF: 221.05,
    buyer: "Nationwide Arena Partners",
    seller: "Columbus Office Trust",
    recordedDate: new Date("2025-05-09"),
    instrumentNumber: "2025-0509-007",
    source: "Franklin County Recorder",
    aiInsight: "First trophy office sale in the CBD exceeding $200/SF since Q1 2023. Buyer is a JV between local developer and Chicago-based family office — signals renewed institutional confidence in Columbus CBD.",
  },
  {
    id: "txn_004",
    propertyId: "prop_013",
    transactionType: "sale",
    price: 49000000,
    pricePerSF: 98.00,
    buyer: "Groveport Logistics Trust",
    seller: "ProLogis Columbus LP",
    recordedDate: new Date("2025-05-08"),
    instrumentNumber: "2025-0508-012",
    source: "Franklin County Recorder",
    aiInsight: "Largest single-asset industrial sale in Franklin County YTD. Cap rate estimated at 4.9% — aggressive pricing reflects Rickenbacker proximity premium. 3 adjacent parcels remain under same seller ownership.",
  },
  {
    id: "txn_005",
    propertyId: "prop_010",
    transactionType: "sale",
    price: 41500000,
    pricePerSF: 145.61,
    buyer: "Capitol Square Partners",
    seller: "Dublin Granville Realty Trust",
    recordedDate: new Date("2025-05-07"),
    instrumentNumber: "2025-0507-021",
    source: "Franklin County Recorder",
    aiInsight: "240-unit multifamily traded at $173k/door — 12% below replacement cost. Seller is a trust entity registered in 2008 with no prior Columbus transactions. Potential estate disposition.",
  },
  {
    id: "txn_006",
    propertyId: "prop_014",
    transactionType: "sale",
    price: 28500000,
    pricePerSF: 146.15,
    buyer: "German Village Residences LP",
    seller: "Broad Street Capital LLC",
    recordedDate: new Date("2025-05-06"),
    instrumentNumber: "2025-0506-008",
    source: "Franklin County Recorder",
    aiInsight: "168-unit German Village asset at $170k/door. Buyer LP structure suggests new equity raise — first acquisition for this entity. Principal address traces to Cincinnati-based family office entering Columbus market.",
  },
  {
    id: "txn_007",
    propertyId: "prop_005",
    transactionType: "sale",
    price: 14800000,
    pricePerSF: 205.56,
    buyer: "Dublin Corporate Park LP",
    seller: "Nationwide Life Insurance Co",
    recordedDate: new Date("2025-05-05"),
    instrumentNumber: "2025-0505-014",
    source: "Franklin County Recorder",
    aiInsight: "Nationwide disposition of non-core asset — 3rd office sold by this seller in 8 months. Dublin Corridor office fundamentals improving with Intel chip fab hiring surge.",
  },
  {
    id: "txn_008",
    propertyId: "prop_002",
    transactionType: "sale",
    price: 18200000,
    pricePerSF: 82.73,
    buyer: "Rickenbacker Holdings LLC",
    seller: "Ohio Valley Logistics Inc",
    recordedDate: new Date("2025-05-03"),
    instrumentNumber: "2025-0503-019",
    source: "Franklin County Recorder",
    aiInsight: "Buyer has acquired 4 assets near Rickenbacker International in 18 months. Entity registered Oct 2023 with Columbus principal — likely local operator capitalizing on air cargo volume growth.",
  },
  {
    id: "txn_009",
    propertyId: "prop_001",
    transactionType: "sale",
    price: 9800000,
    pricePerSF: 202.06,
    buyer: "Polaris Corporate Center LLC",
    seller: "JPMorgan Chase Asset Mgmt",
    recordedDate: new Date("2025-04-29"),
    instrumentNumber: "2025-0429-006",
    source: "Franklin County Recorder",
    aiInsight: "JPMorgan disposal of Polaris-area office below 2021 peak pricing by ~18%. Buyer LLC formed 45 days prior to close — potential owner-occupant acquisition.",
  },
  {
    id: "txn_010",
    propertyId: "prop_009",
    transactionType: "sale",
    price: 5200000,
    pricePerSF: 100.00,
    buyer: "Morse Road Ventures Trust",
    seller: "Kroger Real Estate LLC",
    recordedDate: new Date("2025-04-25"),
    instrumentNumber: "2025-0425-033",
    source: "Franklin County Recorder",
    aiInsight: "Kroger vacancy disposition — former distribution center dark since 2023. Adjacent parcel sold 90 days ago at $118/SF. Owner entity filed as trust with 2 named trustees — estate management pattern.",
  },
];

export const MOCK_PERMITS = [
  {
    id: "permit_001",
    propertyId: "prop_007",
    permitType: "new_construction",
    estimatedValue: 8500000,
    applicant: "NorthPoint Development LLC",
    description: "New 45,000 SF speculative industrial warehouse. Tilt-wall construction, 32' clear height, 8 dock doors, 2 grade-level doors. HVAC roughed for future cold storage.",
    filingDate: new Date("2025-05-13"),
    status: "approved",
    aiInsight: "First new spec industrial in Corporate Exchange submarket in 8 months. 32' clear height spec implies logistics/e-commerce target tenant. Similar product in Rickenbacker is 97% leased.",
  },
  {
    id: "permit_002",
    propertyId: "prop_015",
    permitType: "renovation",
    estimatedValue: 1200000,
    applicant: "German Village Dev Partners",
    description: "Interior build-out of 8,400 SF ground floor retail space. New storefront glazing, mechanical upgrades, ADA compliance improvements. Permit for future food & beverage tenant.",
    filingDate: new Date("2025-05-11"),
    status: "pending",
    aiInsight: "German Village retail vacancy at 5-year low. F&B build-out spec suggests anchor tenant deal already signed — common pre-announcement permit pattern.",
  },
  {
    id: "permit_003",
    propertyId: "prop_011",
    permitType: "renovation",
    estimatedValue: 3400000,
    applicant: "East Broad Industrial LLC",
    description: "Roof replacement, dock door modernization (12 new hydraulic levelers), and LED lighting upgrade throughout 120,000 SF warehouse. Electrical service upgrade to 3,000A.",
    filingDate: new Date("2025-05-09"),
    status: "approved",
    aiInsight: "Cap-ex investment suggests owner preparing asset for refinance or sale. Electrical upgrade to 3,000A supports advanced manufacturing or data center conversion.",
  },
  {
    id: "permit_004",
    propertyId: "prop_006",
    permitType: "renovation",
    estimatedValue: 2100000,
    applicant: "Short North Capital Group",
    description: "Full 3rd floor tenant improvement. Open office conversion, polished concrete floors, exposed ceiling systems, 2 conference suites. Spec suite for creative/tech tenant.",
    filingDate: new Date("2025-05-08"),
    status: "approved",
    aiInsight: "Short North office demand recovering — spec suite investment rare post-pandemic. Creative/tech fit-out spec targets Nationwide Children's Hospital innovation district overflow.",
  },
  {
    id: "permit_005",
    propertyId: "prop_004",
    permitType: "demolition",
    estimatedValue: 450000,
    applicant: "Easton Retail Trust",
    description: "Selective interior demolition of 12,000 SF former anchor tenant space. Asbestos abatement per OEPA protocol. Structural assessment for reconfiguration.",
    filingDate: new Date("2025-05-06"),
    status: "pending",
    aiInsight: "Anchor tenant vacancy at Easton-adjacent strip — demolition permit precedes repositioning. Easton market fundamentals strong; redevelopment for QSR or fitness use likely.",
  },
  {
    id: "permit_006",
    propertyId: "prop_013",
    permitType: "new_construction",
    estimatedValue: 22000000,
    applicant: "Groveport Expansion LLC",
    description: "Phase 2 expansion: 200,000 SF cross-dock warehouse addition. 36' clear height, 50 dock doors, truck court expansion, EV charging infrastructure (80 stations).",
    filingDate: new Date("2025-05-02"),
    status: "approved",
    aiInsight: "Phase 2 expansion on recently traded asset signals immediate value-add play. EV charging scale (80 stations) suggests large fleet operator tenant — Amazon or similar.",
  },
  {
    id: "permit_007",
    propertyId: "prop_003",
    permitType: "renovation",
    estimatedValue: 880000,
    applicant: "Dublin Square Partners",
    description: "Façade renovation, parking lot resurfacing, monument sign replacement. Brand refresh for 32,000 SF neighborhood retail center.",
    filingDate: new Date("2025-04-30"),
    status: "approved",
    aiInsight: "Cosmetic refresh post lease-up — 5 of 8 bays confirmed leased per county records. Remaining vacancy ideal approach opportunity before rents rise.",
  },
];

export const MOCK_ENTITY_FILINGS = [
  {
    id: "ef_001",
    entityName: "Groveport Expansion LLC",
    filingType: "formation",
    state: "OH",
    filingDate: new Date("2025-05-01"),
    registeredAgent: "CT Corporation System",
    principalAddress: "1 Nationwide Plaza, Columbus OH 43215",
    aiInsight: "New LLC formed 11 days before permit application on Groveport asset. Principal address traces to Nationwide Realty office — subsidiary formation pattern suggests institutional-grade development underway.",
  },
  {
    id: "ef_002",
    entityName: "Franklin Industrial Opportunity Fund I LLC",
    filingType: "formation",
    state: "OH",
    filingDate: new Date("2025-05-08"),
    registeredAgent: "National Registered Agents Inc",
    principalAddress: "200 E Broad St Ste 3100, Columbus OH 43215",
    aiInsight: "Fund vehicle formation with 'Opportunity Fund' naming — suggests equity raise for multi-asset acquisition strategy. Principal address is law firm commonly used by out-of-state investors entering Columbus.",
  },
  {
    id: "ef_003",
    entityName: "Dublin Granville Realty Trust",
    filingType: "dissolution",
    state: "OH",
    filingDate: new Date("2025-05-09"),
    principalAddress: "6100 Riverside Dr, Dublin OH 43017",
    aiInsight: "Trust dissolution 2 days after deed transfer recorded — confirms wind-down following asset sale. Beneficial interest distributed to 3 heirs per trust agreement. Remaining portfolio may include 2 additional Dublin properties.",
  },
  {
    id: "ef_004",
    entityName: "Rickenbacker Air Commerce LLC",
    filingType: "formation",
    state: "OH",
    filingDate: new Date("2025-05-11"),
    registeredAgent: "Statutory Agent Solutions",
    principalAddress: "4200 E 5th Ave, Columbus OH 43219",
    aiInsight: "Freight-specific LLC name with Rickenbacker address — formation pattern consistent with new air cargo operator establishing local presence. Columbus-CMH cargo tonnage up 18% YTD.",
  },
  {
    id: "ef_005",
    entityName: "Westerville Medical Properties LLC",
    filingType: "formation",
    state: "OH",
    filingDate: new Date("2025-05-12"),
    registeredAgent: "CT Corporation System",
    principalAddress: "8000 Walton Pkwy Ste 260, New Albany OH 43054",
    aiInsight: "Healthcare REIT subsidiary formation in Westerville — Mount Carmel Health System announcing $180M expansion creates demand signal. Medical office supply in Westerville is 6-year low.",
  },
  {
    id: "ef_006",
    entityName: "Capitol Square Partners",
    filingType: "amendment",
    state: "OH",
    filingDate: new Date("2025-05-13"),
    principalAddress: "100 S 3rd St, Columbus OH 43215",
    aiInsight: "Registered agent change from individual to CT Corporation — professional agent switch common before capital raise or institutional JV. New registered address is downtown law firm.",
  },
];

export const MOCK_OPPORTUNITIES = [
  {
    id: "opp_001",
    propertyId: "prop_009",
    score: 94,
    narrative: "Former Kroger distribution center dark since 2023. Adjacent parcel sold 90 days ago at $118/SF — a 47% premium over this property's last trade price. Owner entity filed as trust with 2 named trustees, classic estate disposition pattern. Asset is 52,000 SF on 4.2 acres with E-1 zoning, ideal for last-mile logistics or self-storage conversion. Replacement cost conservatively estimated at $8.2M; current ask of $5.2M represents 37% discount. Estimated opportunity value: $12.5M stabilized.",
    factors: [
      { label: "Distressed Ownership", weight: 28, description: "Trust dissolution filing indicates likely forced sale" },
      { label: "Below Market Pricing", weight: 24, description: "37% below replacement cost, 47% below adjacent comp" },
      { label: "Market Demand", weight: 22, description: "Last-mile industrial vacancy in Franklin County at 1.2%" },
      { label: "Redevelopment Potential", weight: 20, description: "E-1 zoning allows industrial, retail, and self-storage" },
    ],
    estimatedValue: 12500000,
    recommendedAction: "Approach trustee directly before listing. Contact Estate of [Seller] c/o Columbus Trust Administration at 614-555-0142.",
  },
  {
    id: "opp_002",
    propertyId: "prop_011",
    score: 91,
    narrative: "1985-vintage industrial building undergoing $3.4M capital reinvestment — dock modernization, roof replacement, electrical upgrade to 3,000A. Pattern consistent with pre-sale preparation. Owner LLC has held asset since 2017 purchase at $7.1M. With $3.4M capex, total basis ~$10.5M. Comparable industrial in Eastland corridor trading at $120-140/SF; building at 120,000 SF implies exit value of $14.4-16.8M. Ideal value-add play for buyer willing to complete lease-up.",
    factors: [
      { label: "Pre-Sale Signal", weight: 30, description: "Cap-ex investment pattern matches 12-24 month exit thesis" },
      { label: "Value Creation", weight: 25, description: "3,000A electrical enables advanced manufacturing premium" },
      { label: "Basis Advantage", weight: 25, description: "$87/SF total basis vs $120-140/SF market comps" },
      { label: "Submarket Strength", weight: 20, description: "Eastland industrial vacancy at 3.1% and declining" },
    ],
    estimatedValue: 15600000,
    recommendedAction: "Contact East Broad Industrial LLC management directly. Permit applicant name may match operating principal.",
  },
  {
    id: "opp_003",
    propertyId: "prop_003",
    score: 87,
    narrative: "32,000 SF neighborhood retail center in Dublin showing strong lease-up signal — 5 of 8 bays now occupied per permit application notes. Recent façade renovation and parking improvements underway. Dublin retail fundamentals excellent: average household income $142K within 3-mile radius, retail vacancy below 3%. Owner is a trust entity (Dublin Square Partners) with no acquisition activity since 2019. Remaining vacancy of 3 bays (~12,000 SF) at $28-32/SF NNN would stabilize NOI to justify $7.5-8.5M valuation.",
    factors: [
      { label: "Lease-Up Momentum", weight: 32, description: "62.5% leased and improving; renovation signals confidence" },
      { label: "Demographics", weight: 28, description: "$142K avg HHI, high foot traffic corridor" },
      { label: "Seller Profile", weight: 22, description: "Trust ownership with no recent activity — passive seller" },
      { label: "Upside on Vacancy", weight: 18, description: "3 bays of upside at market rents = $340K additional NOI" },
    ],
    estimatedValue: 8000000,
    recommendedAction: "Approach ownership before listing. Trust dissolution filing (Dublin Granville) nearby suggests family is liquidating Columbus assets.",
  },
  {
    id: "opp_004",
    propertyId: "prop_006",
    score: 82,
    narrative: "Short North/Goodale Blvd office undergoing spec suite conversion targeting creative/tech tenants. Owner Short North Capital Group has held since 2018 at $7.4M basis. Building 41,000 SF, 3 floors. Currently 65% occupied. New spec suite investment of $2.1M signals confidence in lease-up. Short North tech demand driven by Nationwide Children's Hospital innovation campus 4 blocks north. Comparable creative office at $32-38/SF NNN; full lease-up would generate ~$1.4M NOI = $17.5M stabilized value at 8% cap.",
    factors: [
      { label: "Location Premium", weight: 30, description: "Short North most sought-after Columbus creative office district" },
      { label: "Demand Catalyst", weight: 28, description: "Children's Hospital innovation campus driving tech tenant demand" },
      { label: "Value Creation", weight: 22, description: "Spec suite targets premium rent segment; current basis below market" },
      { label: "Ownership Tenure", weight: 20, description: "7-year hold with spec invest suggests near exit window" },
    ],
    estimatedValue: 16000000,
    recommendedAction: "Engage Short North Capital Group principal directly. Building not listed — off-market approach preferred.",
  },
  {
    id: "opp_005",
    propertyId: "prop_004",
    score: 78,
    narrative: "Easton-adjacent strip center with anchor vacancy — demolition permit filed for 12,000 SF reconfiguration. Easton Trade Area fundamentals among strongest in Central Ohio. Trust ownership (Easton Retail Trust) unchanged since 2020. Redevelopment of former anchor space for QSR pad sites could yield 40-60% NOI increase. Permit filing indicates active plans; approaching during demolition phase may unlock pre-approval deal.",
    factors: [
      { label: "Trade Area Quality", weight: 30, description: "Easton Trade Area: $156K avg HHI, 8M+ annual visitors" },
      { label: "Repositioning Signal", weight: 28, description: "Demolition permit = active redevelopment in progress" },
      { label: "QSR Demand", weight: 22, description: "3 national QSR chains actively seeking Easton-adjacent pads" },
      { label: "Ownership Type", weight: 20, description: "Trust ownership with no financing activity since 2020" },
    ],
    estimatedValue: 7200000,
    recommendedAction: "Contact Easton Retail Trust trustees via county recorder records. Approach timing: after demolition complete, before permit issued for redevelopment.",
  },
  {
    id: "opp_006",
    propertyId: "prop_001",
    score: 74,
    narrative: "Polaris-area office acquired below market by new LLC formed 45 days before close — owner-occupant acquisition pattern. JPMorgan disposal at 18% below 2021 peak pricing. Building 48,500 SF, 2008 vintage, fully air-conditioned. If owner-occupant occupies 60% and leases remaining 40% (19,400 SF at $22/SF NNN), generates $427K NOI at fully-leased = $5.3M value on investment of $9.8M. Polaris office rents recovering with Intel Fab hiring drawing supply chain firms.",
    factors: [
      { label: "Below-Peak Pricing", weight: 28, description: "18% below 2021 peak; market recovery underway" },
      { label: "Intel Corridor", weight: 26, description: "Intel chip fab creating office demand in Polaris/New Albany corridor" },
      { label: "Institutional Exit", weight: 24, description: "JPMorgan portfolio rationalization may include additional assets" },
      { label: "New Owner Type", weight: 22, description: "LLC formation pattern suggests owner-user — may flip lease-up play" },
    ],
    estimatedValue: 13000000,
    recommendedAction: "Monitor Polaris Corporate Center LLC for 12-24 months. If owner-occupant, approach for sale-leaseback as they mature.",
  },
  {
    id: "opp_007",
    propertyId: "prop_015",
    score: 69,
    narrative: "Mixed-use asset in German Village — F&B tenant permit filed for 8,400 SF ground floor. Short North/German Village corridor seeing 15% rent growth YTD. Asset 28,000 SF on S High St, 2017 vintage. Current ownership LLC (German Village Dev Partners) has operated asset 3 years. If anchor F&B tenant confirmed and upper floors fully leased at $2.80/SF/mo residential, stabilized NOI ~$520K = $7.5M at 7% cap, vs last trade of $7.2M.",
    factors: [
      { label: "Rent Growth", weight: 30, description: "German Village seeing 15% YOY rent growth — best in Columbus" },
      { label: "Anchor Tenant Signal", weight: 28, description: "F&B permit suggests signed LOI with anchor restaurant" },
      { label: "Near Stabilization", weight: 22, description: "Asset approaching full lease-up; limited further upside but stable" },
      { label: "Location", weight: 20, description: "S High St South: emerging dining corridor with 3 new concepts" },
    ],
    estimatedValue: 7800000,
    recommendedAction: "Current value near stabilized; only pursue if owner willing to sell below $7.5M. Track for 90 days.",
  },
  {
    id: "opp_008",
    propertyId: "prop_002",
    score: 65,
    narrative: "220,000 SF Rickenbacker area industrial recently traded at $82.73/SF to new buyer (Rickenbacker Holdings LLC). Buyer entity formed Oct 2023, now holds 4 assets totaling 680,000 SF near Rickenbacker International Airport. Air cargo volume at CMH up 18% YTD. Buyer may be positioning for aggregation and portfolio sale to REIT. Watch for any listing activity — could be a broker introduction opportunity.",
    factors: [
      { label: "Aggregation Pattern", weight: 32, description: "Buyer assembling Rickenbacker portfolio — possible REIT exit" },
      { label: "Air Cargo Growth", weight: 28, description: "CMH cargo tonnage +18% YTD; Amazon Air expanding operations" },
      { label: "Submarket Scarcity", weight: 24, description: "Rickenbacker industrial vacancy: 0.8% — essentially zero" },
      { label: "New Ownership", weight: 16, description: "New owner 12 months in — too early for exit, but relationship window" },
    ],
    estimatedValue: 24000000,
    recommendedAction: "Build relationship with Rickenbacker Holdings LLC principal now. Offer market intel. Position as exclusive broker for eventual portfolio sale.",
  },
];

export const MOCK_MARKET_STATS = {
  totalTransactionVolume: 248700000,
  totalTransactions: 47,
  avgPricePerSF: {
    Industrial: 96.4,
    Office: 198.2,
    Retail: 118.7,
    Multifamily: 159.3,
  },
  permitActivity: {
    newConstruction: 8,
    renovation: 22,
    demolition: 4,
  },
  entityFilings: {
    formations: 14,
    dissolutions: 3,
    amendments: 7,
  },
  opportunityAlerts: 8,
  weeklyTrend: [
    { week: "W1 Apr", volume: 42.1, transactions: 8 },
    { week: "W2 Apr", volume: 38.7, transactions: 7 },
    { week: "W3 Apr", volume: 61.2, transactions: 11 },
    { week: "W4 Apr", volume: 29.4, transactions: 5 },
    { week: "W1 May", volume: 77.3, transactions: 16 },
  ],
  monthlyTrend: [
    { month: "Jun '24", volume: 156.2, transactions: 31 },
    { month: "Jul '24", volume: 134.8, transactions: 27 },
    { month: "Aug '24", volume: 189.3, transactions: 38 },
    { month: "Sep '24", volume: 142.1, transactions: 29 },
    { month: "Oct '24", volume: 201.7, transactions: 42 },
    { month: "Nov '24", volume: 167.4, transactions: 34 },
    { month: "Dec '24", volume: 98.2, transactions: 19 },
    { month: "Jan '25", volume: 121.6, transactions: 24 },
    { month: "Feb '25", volume: 178.9, transactions: 36 },
    { month: "Mar '25", volume: 219.4, transactions: 44 },
    { month: "Apr '25", volume: 171.4, transactions: 31 },
    { month: "May '25", volume: 248.7, transactions: 47 },
  ],
  topBuyers: [
    { name: "NorthPoint Development LLC", volume: 51500000, count: 3 },
    { name: "Groveport Logistics Trust", volume: 49000000, count: 1 },
    { name: "Capitol Square Partners", volume: 41500000, count: 1 },
    { name: "Amazon.com Services LLC", volume: 36000000, count: 1 },
    { name: "German Village Residences LP", volume: 28500000, count: 1 },
  ],
  topSellers: [
    { name: "ProLogis Columbus LP", volume: 49000000, count: 1 },
    { name: "Nationwide Life Insurance Co", volume: 42800000, count: 3 },
    { name: "New Albany Industrial Partners", volume: 36000000, count: 1 },
    { name: "Midwest Industrial REIT", volume: 16500000, count: 1 },
    { name: "Columbus Office Trust", volume: 21000000, count: 1 },
  ],
};

export const MOCK_BRIEFING_SUMMARY = `3 new industrial transactions closed in Franklin County this week totaling $71.7M — strongest 5-day industrial volume since Q3 2024. NorthPoint Development filed a permit for the first speculative warehouse in Corporate Exchange submarket in 8 months, signaling renewed confidence in the corridor. High-priority: former Kroger distribution center on Morse Rd shows estate-disposition pattern with adjacent comp at 47% premium — Opportunity Score 94/100.`;

export const MOCK_USER = {
  name: "Marcus Webb",
  firm: "Webb Commercial Realty",
  email: "marcus@webbcommercial.com",
  role: "Broker",
  counties: ["Franklin"],
  propertyTypes: ["Industrial", "Office", "Retail"],
  briefingTime: "07:00",
};
